"""
Django settings for Earn9Game project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""


from pathlib import Path
from django.utils.translation import gettext_lazy as _
from dotenv import load_dotenv
import os
from decouple import config
from datetime import timedelta
from django.conf import settings
from django.core.cache import cache
# cache.clear()
# https://codetap.org/project/archery-game  ,  # https://github.com/he-is-talha/html-css-javascript-games?tab=readme-ov-file


BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-u(wq4qo@n6n5my#l9rl9uc$i5y8@-$@w@^twigqs%b_sqj(x-u'

DEBUG = True # os.environ.get("DEBUG", 'True').lower() in ['true', 'yes', '1'] # os.environ.get("DEBUG", 'True').lower() in ['true', 'yes', '1']  # true
  
ALLOWED_HOSTS = ['*', 'http://127.0.0.1:8001/', 'http://103.53.162.29/',  '192.168.18.53', 'http://192.168.18.53:8000', 'https://www.arshadali.space' ] 
 
URL = "http://127.0.0.1:8000" 

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles', 
    
    'rest_framework_simplejwt.token_blacklist',
    'AccountApp',
    'GameApp',
    'MenuApp',
    'channels', 
    'gmailapi_backend',
]
 
AUTHENTICATION_BACKENDS = [
    'AccountApp.backends.PhoneBackend',  # For phone auth
    'django.contrib.auth.backends.ModelBackend'  # For email (default)
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware', 
]

ROOT_URLCONF = 'Earn9Game.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join('templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'Earn9Game.wsgi.application'

ASGI_APPLICATION = 'Earn9Game.asgi.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
         

    },
}
 

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
 

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = False

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') 
 
TWILIO_ACCOUNT_SID = config('TWILIO_ACCOUNT_SID')
TWILIO_AUTH_TOKEN = config('TWILIO_AUTH_TOKEN')
TWILIO_WHATSAPP_NUMBER = config('TWILIO_WHATSAPP_NUMBER')

# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = "smtp.forpsi.com"
# EMAIL_PORT = 465  # Use 465 for SSL or 587 for TLS
# EMAIL_USE_TLS = False  # Set True for TLS
# EMAIL_USE_SSL = True  # Set False for TLS (Mutually Exclusive)
# EMAIL_HOST_USER = "noreply@illustre.hu"
# EMAIL_HOST_PASSWORD = "illustrE1648!"
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'AccountApp.db_Profile' 



# ---------------------------------------------------------------------------------------------- > 
 
BASE_URL = os.environ.get("BASE_URL", default="http://127.0.0.1:8000")

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:3000",
]


CORS_ALLOW_HEADERS = [
    'content-type',
    'x-csrftoken',
    'authorization',
]

SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = False 
CSRF_COOKIE_SECURE = False  
SESSION_COOKIE_AGE = 3600

LANGUAGES = [
    ("en", _("English")),
    ("fr", _("French")),
    ("ar", _("Arabic")),
    ("de", _("German")),
    ('hu', _('Hungarian')), 
]

LOGIN_URL = "/signin/"
LOGOUT_REDIRECT_URL = "/admin/"

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'EXCEPTION_HANDLER': 'Earn9Game.utils_file.exception_handler.custom_exception_handler',
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

REST_FRAMEWORK['DEFAULT_AUTHENTICATION_CLASSES'] += (
    'rest_framework_simplejwt.authentication.JWTAuthentication',
    # 'EXCEPTION_HANDLER': 'prior_cash.utils.exception_handler.custom_exception_handler',
)

SIMPLE_JWT = { 
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1), # hours = 1, munits=10
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),  # days = 1, munits=10
    # 'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    # 'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',), 
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',
    'UPDATE_LAST_LOGIN': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': settings.SECRET_KEY,
    'VERIFYING_KEY': None,
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}
 
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
}
 

 