# Generated by Django 5.0.6 on 2025-07-01 18:40

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.PositiveIntegerField(default=0)),
                ('last_active', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('transaction_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccountApp.player')),
            ],
        ),
        migrations.CreateModel(
            name='db_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Username')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Email')),
                ('db_phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Phone Number')),
                ('db_fullname', models.CharField(max_length=255, verbose_name='Full Name')),
                ('db_country_address', models.TextField(blank=True, max_length=255, verbose_name='Country Address')),
                ('db_photo', models.CharField(max_length=25, verbose_name='Image')),
                ('expired_time_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Expired Time Start')),
                ('expired_time_end', models.DateTimeField(blank=True, null=True, verbose_name='Expired Time End')),
                ('code_pin', models.CharField(blank=True, max_length=125, verbose_name='Code Pin')),
                ('auth_token', models.CharField(max_length=255, verbose_name='Auth Token')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is Staff')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verify')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='db_profile',
            constraint=models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('email',), name='unique_email'),
        ),
        migrations.AddConstraint(
            model_name='db_profile',
            constraint=models.UniqueConstraint(condition=models.Q(('db_phone_number', ''), _negated=True), fields=('db_phone_number',), name='unique_phone'),
        ),
    ]
