# Generated by Django 5.0.6 on 2025-07-01 18:40

import GameApp.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AccountApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('current_bid_total', models.JSONField(blank=True, default=dict, max_length=10000)),
                ('timer', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dice_Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('current_bid', models.JSONField(blank=True, default=dict, max_length=10000)),
                ('timer', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('current_bid', models.JSONField(blank=True, default=dict)),
                ('timer', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RocketGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('current_bid', models.IntegerField(null=True)),
                ('timer', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ColorGameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_game_id', models.CharField(default=GameApp.models.generate_timestamp_id, max_length=14)),
                ('status', models.CharField(choices=[('WAIT', 'Waiting'), ('ACTIVE', 'Active'), ('PROCESSING', 'Processing Results'), ('RESULTS', 'Showing Results'), ('DONE', 'Completed')], default='WAIT', max_length=10)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('result_start', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('random_number', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds_color', to='GameApp.colorgame')),
            ],
        ),
        migrations.AddField(
            model_name='colorgame',
            name='current_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_game_round_color', to='GameApp.colorgameround'),
        ),
        migrations.CreateModel(
            name='ColorPlayerBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_detail', models.JSONField(default=GameApp.models.default_player_detail_color, max_length=100000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids_color', to='AccountApp.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids_color', to='GameApp.colorgameround')),
            ],
        ),
        migrations.CreateModel(
            name='ColorPlayerResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_bet_Color', models.IntegerField()),
                ('amount_bet_Size', models.IntegerField()),
                ('amount_bet_Exact_Number', models.IntegerField()),
                ('amount_won_loss', models.IntegerField()),
                ('result_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccountApp.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameApp.colorgameround')),
            ],
        ),
        migrations.CreateModel(
            name='ConnectDotGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_a_bet_amount', models.PositiveIntegerField()),
                ('player_b_bet_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('expired', 'Expired')], default='waiting', max_length=10)),
                ('player_a_channel', models.CharField(blank=True, max_length=255)),
                ('player_b_channel', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dot_games_as_a', to=settings.AUTH_USER_MODEL)),
                ('player_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dot_games_as_b', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectDotRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_status', models.CharField(choices=[('PLAYER_A_TURN', 'Player A Turn'), ('PLAYER_B_TURN', 'Player B Turn'), ('RESULT', 'Result'), ('EXPIRED', 'Expired')], max_length=50)),
                ('player_a_detail', models.JSONField(default=GameApp.models.default_player_detail_dot, max_length=100000)),
                ('player_b_detail', models.JSONField(default=GameApp.models.default_player_detail_dot, max_length=100000)),
                ('timer_remaining', models.PositiveIntegerField(default=150)),
                ('turn_time_remaining', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='GameApp.connectdotgame')),
            ],
        ),
        migrations.CreateModel(
            name='ConnectDotResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_won_loss', models.IntegerField()),
                ('result_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccountApp.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameApp.connectdotround')),
            ],
        ),
        migrations.CreateModel(
            name='Dice_GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WAIT', 'Waiting'), ('ACTIVE', 'Active'), ('RESULTS', 'Showing Results'), ('DONE', 'Completed')], default='WAIT', max_length=10)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('result_start', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dice1', models.PositiveIntegerField(null=True)),
                ('dice2', models.PositiveIntegerField(null=True)),
                ('total', models.PositiveIntegerField(null=True)),
                ('multiplyer_number', models.JSONField(default=dict)),
                ('exact_number_on_multiplyer', models.JSONField(default=dict)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds_dice', to='GameApp.dice_game')),
            ],
        ),
        migrations.AddField(
            model_name='dice_game',
            name='current_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_game_round_dice', to='GameApp.dice_gameround'),
        ),
        migrations.CreateModel(
            name='Dice_PlayerBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(blank=True, choices=[('DOWN', 'Down'), ('MIDDLE', 'Middle'), ('UP', 'Up')], max_length=6, null=True)),
                ('amount_bet_side', models.PositiveIntegerField(blank=True, null=True)),
                ('exact_number', models.PositiveIntegerField(blank=True, null=True)),
                ('amount_bet_exact', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids_dice', to='AccountApp.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids_dice', to='GameApp.dice_gameround')),
            ],
        ),
        migrations.CreateModel(
            name='Dice_PlayerResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_bet_side', models.IntegerField()),
                ('amount_bet_exact', models.IntegerField()),
                ('amount_won_loss', models.IntegerField()),
                ('result_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccountApp.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameApp.dice_gameround')),
            ],
        ),
        migrations.CreateModel(
            name='FootballGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_a_bet_amount', models.PositiveIntegerField()),
                ('player_b_bet_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('expired', 'Expired')], default='waiting', max_length=10)),
                ('player_a_channel', models.CharField(blank=True, max_length=255)),
                ('player_b_channel', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_a', to=settings.AUTH_USER_MODEL)),
                ('player_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_b', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FootballRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_status', models.CharField(choices=[('PLAYER_A_TURN', 'Player A Turn'), ('PLAYER_B_TURN', 'Player B Turn'), ('RESULT', 'Result'), ('EXPIRED', 'Expired')], max_length=50)),
                ('player_a_detail', models.JSONField(default=GameApp.models.default_player_detail, max_length=100000)),
                ('player_b_detail', models.JSONField(default=GameApp.models.default_player_detail, max_length=100000)),
                ('timer_remaining', models.PositiveIntegerField(default=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='GameApp.footballgame')),
            ],
        ),
        migrations.CreateModel(
            name='FootBallResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_won_loss', models.IntegerField()),
                ('result_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccountApp.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameApp.footballround')),
            ],
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('WAIT', 'Waiting'), ('ACTIVE', 'Active'), ('RESULTS', 'Showing Results'), ('DONE', 'Completed')], default='WAIT', max_length=10)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timer', models.IntegerField(default=0)),
                ('result_duration', models.PositiveIntegerField(default=3)),
                ('result_start', models.DateTimeField(null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='GameApp.game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='current_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_game_round', to='GameApp.gameround'),
        ),
        migrations.CreateModel(
            name='GuessNumberGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_game_detail', models.JSONField(default=GameApp.models.default_player_detail_guess, max_length=100000)),
                ('player_channel', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player_auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guess_games_as', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('side', models.CharField(choices=[('NUM', 'Number'), ('PIC', 'Picture')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='AccountApp.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='GameApp.gameround')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_bet', models.IntegerField()),
                ('amount_won_loss', models.IntegerField()),
                ('result_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccountApp.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameApp.gameround')),
            ],
        ),
        migrations.CreateModel(
            name='RocketGameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WAIT', 'Waiting'), ('ACTIVE', 'Active'), ('FLY', 'Fly'), ('DONE', 'Completed')], default='WAIT', max_length=10)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(null=True)),
                ('random_number_flee', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('state_Rocket', models.JSONField(default=GameApp.models.detail_game_state_Rocket, max_length=100000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds_rocket', to='GameApp.rocketgame')),
            ],
        ),
        migrations.AddField(
            model_name='rocketgame',
            name='current_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_game_round_rocket', to='GameApp.rocketgameround'),
        ),
        migrations.CreateModel(
            name='RocketPlayerBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_user_guess', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('mind_Change_user_guess', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('amount_bet', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids_rocket', to='AccountApp.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids_rocket', to='GameApp.rocketgameround')),
            ],
        ),
        migrations.CreateModel(
            name='RocketPlayerResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_bet', models.IntegerField()),
                ('result_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccountApp.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameApp.rocketgameround')),
            ],
        ),
        migrations.CreateModel(
            name='SpinWheelRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WAIT', 'Waiting'), ('ACTIVE', 'Active'), ('SPIN', 'Spin'), ('RESULT', 'Result'), ('DONE', 'Completed')], default='WAIT', max_length=10)),
                ('amount_bet', models.IntegerField(blank=True, null=True)),
                ('timer', models.IntegerField(default=0)),
                ('game_randomly_prize', models.CharField(max_length=100)),
                ('prize_coins', models.CharField(max_length=100)),
                ('prize_in_side_box', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids_SpinWheel', to='AccountApp.player')),
            ],
        ),
        migrations.AddConstraint(
            model_name='colorplayerbid',
            constraint=models.UniqueConstraint(fields=('player', 'round'), name='unique_player_round_bid_color'),
        ),
        migrations.AddConstraint(
            model_name='dice_playerbid',
            constraint=models.UniqueConstraint(fields=('player', 'round'), name='unique_player_round_bid_dice'),
        ),
        migrations.AlterUniqueTogether(
            name='playerbid',
            unique_together={('player', 'round')},
        ),
        migrations.AddConstraint(
            model_name='rocketplayerbid',
            constraint=models.UniqueConstraint(fields=('player', 'round'), name='unique_player_round_bid_rocket'),
        ),
        migrations.AddConstraint(
            model_name='rocketplayerresult',
            constraint=models.UniqueConstraint(fields=('player', 'round'), name='unique_result_per_player_round'),
        ),
    ]
